version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u AWS -p $(aws ecr get-login-password --region ap-south-1) 632619531167.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - export PYTHONUNBUFFERED=TRUE
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t intel-cloud-optimizations-aws-k8s:latest intel-cloud-optimizations-aws-k8s/.
      - docker tag ecs_sample_app:latest 632619531167.dkr.ecr.us-east-2.amazonaws.com/ecs_sample_app:git
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 632619531167.dkr.ecr.us-east-2.amazonaws.com/intel-cloud-optimizations-aws-k8s
      - echo Writing image definitions file...
      - printf '[{"name":"container","imageUri":"632619531167.dkr.ecr.us-east-2.amazonaws.com/intel-cloud-optimizations-aws-k8s"}]'
