apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "eks-cluster-loanDefault"
  version: "1.23"
  region: "us-east-2"

managedNodeGroups:
- name: "eks-cluster-loanDefault-mng"
  desiredCapacity: 2
  minSize: 1
  maxSize: 2
  volumeSize: 20
  instanceType: "t2.micro"