apiVersion: apps/v1
kind: Deployment
metadata:
  name: "eks-loan-default-app"
  namespace: "loan-default-app"
  labels:
    app: "loan-default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "loan-default"
  template:
    metadata:
      labels:
        app: "loan-default"
    spec:
     serviceAccountName: "loan-default-service-account"
     topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: "loan-default"
     containers:
       - name: "model-image"
         image: 632619531167.dkr.ecr.us-east-2.amazonaws.com/intel-cloud-optimizations-aws-k8s:latest
         ports:
           - containerPort: 80
         imagePullPolicy: "Always"
         resources:
          limits:
            cpu: 500m
          requests:
           cpu: 250m
