version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u AWS -p $(aws ecr get-login-password --region ap-south-1) 832173187970.dkr.ecr.ap-south-1.amazonaws.com
    
  build:
    commands:
      - export PYTHONUNBUFFERED=TRUE
      - export SAGEMAKER_PROJECT_NAME_ID="${SAGEMAKER_PROJECT_NAME}-DeployApptoECS"
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls DeployApplicationToECS/
      - docker build -t ecs_sample_app:latest DeployApplicationToECS/.
      - docker tag ecs_sample_app:latest 832173187970.dkr.ecr.ap-south-1.amazonaws.com/ecs_sample_app:git      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 832173187970.dkr.ecr.ap-south-1.amazonaws.com/ecs_sample_app:git
      